# Generated by Django 3.1.6 on 2021-07-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateField(default='2021-07-04')),
                ('finish_date', models.DateField(default='2021-07-04')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='tasks.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
